### ISSUE TITLE
Are there any instructions on how to use this project

### ISSUE THREAD

**Issue by mlimotte** [wikimedia/operations-debs-kafka#1]
I don't see a README.  Are there any instructions or a quick overview on how to run this and produce a deb?  

Alternatively, is there a pre-built deb for ubuntu trusty?  The "Requirements" at https://github.com/wikimedia/puppet-kafka have a link for "prebuilt .deb" pointing to http://apt.wikimedia.org/wikimedia/pool/universe/k/kafka/ , but that results in a 404 error.

thanks for any clarification.

**Comment by ottomata** [comment]
0.8.2.1 is buildable and built for Trusty and Debian Jessie, woo!
http://apt.wikimedia.org/wikimedia/pool/main/k/kafka/
