### ISSUE TITLE
Debian package for kafka 0.8.2.0

### ISSUE THREAD

**Issue by mantunovic** [wikimedia/operations-debs-kafka#2]
Hi guys,

I was trying to build 0.8.2.0 packages using instructions provided here but not successful so if You manage to do it can You please put them on http://apt.wikimedia.org/wikimedia/pool/main/k/kafka/ as I used Your puppet module for kafka and new version of kafka has a lot of bug fixes and improvements https://archive.apache.org/dist/kafka/0.8.2.0/RELEASE_NOTES.html 

Thank You very much,
Mladen

**Comment by ottomata** [comment]
0.8.2.0 won't be built, but 0.8.2.1 is built and available for Ubuntu Trusty and Debian Jessie!  http://apt.wikimedia.org/wikimedia/pool/main/k/kafka/
